### ISSUE TITLE
ROADMAP v2.0

### ISSUE THREAD

**Issue by davidzwa** [studentenhuisDS4/ds4reboot#212]
**Bugs/issues**
- [x] 1 - Eetlijst if not housemate confirm
~Profile, display_name not properly set.~
- [x] Profile, username autogenerated, inconsisten
- [x] Profile, pre-generate report + confirmation
- [x] 3 - Spelling mistakes (turven bierlijst)
- [x] 4 - Volume audio 50%
- [x] Test SMTP + mail (sendpulse)
- [x] 5 - Uitverhuizen Mail + bugfix
- [ ] Thesau Better mail move-out template
- [x] Thesau HR --> media folder + datamigration + (manual) file_move
- [x] Eetlijst Close list big button
- [x] Direct inschrijven andere dag

**New features**
- [x] Wiki (+CMS)
- [ ] 2 - Google calendar integration (2 tabs: events + keukendienst)
- [ ] Keukendienst page (#227 + frontend)
- [ ] Notification page (custom server API for direct notifications + Firebase notifications)

**New additions**
- [ ] Commission WIKI groups
- [x] Uploading Thesau receipts
