### ISSUE TITLE
ROADMAP v2.1

### ISSUE THREAD

**Issue by davidzwa** [studentenhuisDS4/ds4reboot#241]
Angular frontend:
- [x] Cost dinner
- [ ] View receipts (user) + add by file/camera
- [ ] Manage own receipts (thesau+user), download receipts (thesau)
- [ ] Fix keukendienst receipt upload
- [x] Show beerturf log
- [ ] Admin manage beerturf entries
- [ ] Eetlijst log + manage (admin, thesau)
- [ ] Add turf boete
- [ ] Add split wine modal
- [x] Add profile CRUD
- [x] Add user profile create (admin)
- [x] Add user profile edit (admin)
- [x] Add user profile manage (admin)
- [ ] Add admin page (total balance, fix balance)
- [ ] Add house info page (users)
- [x] Add contact page + home page link

Fixes Angular:
- [x] #248 multi userdinners/async-concurrency

Server:
- [ ] Finish keukendienst API + management
- [ ] Add admin fix balance action
- [ ] Add split wine functionality + check wine balance

Fixes:
- [ ] #238 decimal places wine
- [x] #235 partial kwarg schema 
- [ ] #237 no report bug

Tests:
- [ ] #239 Upload receipts
- [ ] API basic tests (turf, eetlijst, user, hr)
- [ ] (Future) keukendienst
- [x] Fix django tests CI (psycopg2) #243 
- [ ] Fix CI cache (pipenv package folder wrong)

Future updates: 
- [ ] turf-matrix
- [ ] Add stats page
- [x] crate-turf (incl. house)
- [ ] quick log + CRUD (admin vs own turf)
- [ ] boetepanel
- [ ] splitting wine across housemates.
